dist: trusty
sudo: required

services:
  - docker

language: java
jdk:
  - oraclejdk8

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - ./gradlew web:buildDocker
  - docker push solomkinmv/glossary