security.jwt:
  tokenExpirationTime: 15 # minutes
  refreshTokenExpTime: 60 # minutes
  tokenIssuer: http://solomkinmv.github.io
  tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus

spring:
#  datasource.url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  datasource.url: jdbc:h2:./testDb
  h2.console.enabled: true