security.jwt:
  tokenExpirationTime: 600 # minutes
  refreshTokenExpTime: 1800 # minutes
  tokenIssuer: http://solomkinmv.github.io
  tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus

spring:
  datasource.url: jdbc:hsqldb:mem:testDb

translate.key: trnsl.1.1.20170203T233533Z.93a3ca61465d0928.e64b79ae3d8a474cb87ef51e06ab926755908d76