security.jwt:
  tokenExpirationTime: 600 # minutes
  refreshTokenExpTime: 1800 # minutes
  tokenIssuer: http://solomkinmv.github.io
  tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus

spring:
  datasource.url: jdbc:hsqldb:./testDb